// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    MatchingPicture: typeof import('./src/components/MatchingPicture.vue')['default']
  }
}

export { }
